#!/usr/bin/env python3
import argparse, json
from pathlib import Path

def py_repr(obj):
    return repr(obj)

def find_scene(spec, scene_id):
    for s in spec["sequence"]:
        if s["id"] == scene_id:
            return s
    raise KeyError(scene_id)

def balance_call(scene, scale=1.05):
    left = py_repr(scene.get("left", []))
    right = py_repr(scene.get("right", []))
    return f"balance_from_items({left}, {right}, scale={scale})"

def generate(spec):
    title = spec["title"]
    subtitle = spec["subtitle"]
    one_liner = spec["one_liner"]
    video_scene = spec["exports"]["video_scene"]

    main = find_scene(spec, "main_balance")
    after = find_scene(spec, "x_equals_5")
    two_x = find_scene(spec, "two_x")

    main_balance = balance_call(main, scale=1.05)
    after_balance = balance_call(after, scale=1.05)
    two_x_balance = balance_call(two_x, scale=1.02)

    code = f'''# Auto-generated by compile_to_manim.py. Do not edit by hand.
from manim import *
from math_wild import *

config.background_color = BG

TITLE = {title!r}
SUBTITLE = {subtitle!r}
ONE_LINER = {one_liner!r}

def make_header(title=TITLE, subtitle=SUBTITLE):
    return chapter_header(title, subtitle)

def make_main_balance():
    return {main_balance}

def make_after_balance():
    return {after_balance}

def make_two_x_balance():
    return {two_x_balance}

class {video_scene}(Scene):
    def construct(self):
        header = make_header()
        title, subtitle = header
        self.play(FadeIn(title, shift=DOWN*0.2), FadeIn(subtitle, shift=DOWN*0.15))
        self.wait(0.3)

        eq = formula_card({main["equation"]!r}, size=52).next_to(header, DOWN, buff=0.35)
        self.play(Write(eq))

        balance = make_main_balance().shift(DOWN*0.55)
        self.play(Create(balance), run_time=1.25)
        self.wait(0.7)

        note = label_text("两边同时去掉 3：不是搬家，而是保持平衡。", size=26, color=YELLOW, weight=BOLD).to_edge(DOWN)
        self.play(FadeIn(note, shift=UP*0.2))

        eq2 = formula_card("x + 3 − 3 = 8 − 3", size=42).move_to(eq)
        self.play(Transform(eq, eq2))
        self.wait(0.4)

        balance_after = make_after_balance().shift(DOWN*0.55)
        self.play(Transform(balance, balance_after), run_time=1.2)

        eq3 = formula_card("x = 5", size=52).move_to(eq)
        self.play(Transform(eq, eq3), FadeOut(note))
        self.wait(0.8)

        title2 = label_text("另一种平衡", size=44, color=WHITE, weight=BOLD).move_to(title)
        subtitle2 = subtitle_text("2x = 10 也只是同一个规则", size=26).move_to(subtitle)
        eq4 = formula_card({two_x["equation"]!r}, size=50).move_to(eq)
        balance_two = make_two_x_balance().shift(DOWN*0.55)

        self.play(
            Transform(title, title2),
            Transform(subtitle, subtitle2),
            Transform(eq, eq4),
            Transform(balance, balance_two),
            run_time=1.2,
        )
        self.wait(0.7)

        note2 = label_text("两边平均分成 2 份", size=28, color=YELLOW, weight=BOLD).to_edge(DOWN)
        self.play(FadeIn(note2, shift=UP*0.2))

        eq5 = formula_card("x = 5", size=52).move_to(eq)
        balance_result = make_after_balance().shift(DOWN*0.55)
        self.play(Transform(eq, eq5), Transform(balance, balance_result), run_time=1.2)
        self.wait(0.8)

        self.play(FadeOut(balance), FadeOut(note2), eq.animate.shift(UP*0.15))
        summary = label_text({spec["summary"]["line"]!r}, size=34, color=YELLOW, weight=BOLD).next_to(eq, DOWN, buff=0.65)
        self.play(Write(summary))
        self.wait(1.4)

class KF01MainBalance(Scene):
    def construct(self):
        header = make_header()
        self.add(header)
        eq = formula_card("x + 3 = 8", size=52).next_to(header, DOWN, buff=0.35)
        self.add(eq, make_main_balance().shift(DOWN*0.55))

class KF02SubtractThree(Scene):
    def construct(self):
        header = make_header(TITLE, "两边同变，关系不变")
        self.add(header)
        eq = formula_card("x + 3 − 3 = 8 − 3", size=42).next_to(header, DOWN, buff=0.35)
        self.add(eq, make_main_balance().shift(DOWN*0.55))
        self.add(label_text("两边同时去掉 3", size=30, color=YELLOW, weight=BOLD).to_edge(DOWN))

class KF03XEqualsFive(Scene):
    def construct(self):
        header = make_header(TITLE, "隐藏量显现")
        self.add(header)
        eq = formula_card("x = 5", size=52).next_to(header, DOWN, buff=0.35)
        self.add(eq, make_after_balance().shift(DOWN*0.55))

class KF04TwoX(Scene):
    def construct(self):
        header = make_header("另一种平衡", "2x = 10 也只是同一个规则")
        self.add(header)
        eq = formula_card("2x = 10", size=50).next_to(header, DOWN, buff=0.35)
        self.add(eq, make_two_x_balance().shift(DOWN*0.55))

class KF05SplitTwoX(Scene):
    def construct(self):
        header = make_header("另一种平衡", "两边平均分，关系仍然保持")
        self.add(header)
        eq = formula_card("x = 5", size=52).next_to(header, DOWN, buff=0.35)
        self.add(eq, make_after_balance().shift(DOWN*0.55))
        self.add(label_text("每一份：x = 5", size=34, color=YELLOW, weight=BOLD).to_edge(DOWN))

class KF06Summary(Scene):
    def construct(self):
        header = make_header("本章收束", "等号是一种关系，不是一个终点")
        self.add(header)
        eq = formula_card("x + 3 = 8  →  x = 5", size=46).shift(UP*0.15)
        summary = label_text({spec["summary"]["line"]!r}, size=34, color=YELLOW, weight=BOLD).next_to(eq, DOWN, buff=0.65)
        self.add(eq, summary)
'''
    return code

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("spec", default="chapter_spec.json")
    ap.add_argument("--out", default="generated/balance_equations_scene.py")
    args = ap.parse_args()
    spec = json.loads(Path(args.spec).read_text(encoding="utf-8"))
    code = generate(spec)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(code, encoding="utf-8")
    meta = {
        "generated_scene": str(out),
        "video_scene": spec["exports"]["video_scene"],
        "keyframe_scenes": spec["exports"]["keyframe_scenes"],
        "source_spec": args.spec
    }
    (out.parent / "render_metadata.json").write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(meta, ensure_ascii=False, indent=2))

if __name__ == "__main__":
    main()
